alec-kr/F1PyStats

F1PyStats/F1PyStats.py
F1PyStats/constructor_results.py
F1PyStats/driver_results.py
F1PyStats/race_schedule.py
F1PyStats/race_winners.py

I have changed all the string manipulation with f string, and all the function that return a list of element into list comprehension, making them a little faster.

Refactory of the code

---

.github/pull_request_template.md

A pull request template was created in ```.github/pull_request_template.md```, so that all contributors can follow one particular format when submitting pull requests.
This PR fixes #27. 
Contributors will now be greeted with a default template when submitting PRs. They will have to fill out the relevant sections of the template before submitting their PR.

Added pull_request_template

---

.gitignore

Adding Pycharm setting to .gitignore file

Adding Pycharm setting to .gitignore file

---

f1pystats/__init__.py
f1pystats/f1pystats.py
f1pystats/lap_times.py

Added function `lap_times()` in the file `f1pystats.py` to incorporate the functionality to extract lap timings for each driver for a particular year, round and lap. As part of the changes, I added a new class `LapTimes` in the file `lap_times.py`. Also, I appended the new function `lap_times` into the `__init__.py` file.
Implement a function to return the lap times for a specified race #14

Added lap_times() functionality

---

.github/workflows/pylint.yml
f1pystats/f1pystats.py
f1pystats/lap_times.py

Updating the alec-kr-patch-1 branch

Update branch from main

---

f1pystats/driver_info.py
f1pystats/f1pystats.py

Update files similar to the fix made in issue #49
- standardized code format
- more concise function calls
- fix lines exceeding 100 char
- request json by _get_json_content_from_url()
None
None
None

Refactor DriverInfo

---

f1pystats/f1pystats.py
f1pystats/sprint_results.py

do the same things as #51 and #53, to these two new additions.
- SprintResults
- ConstructorInfo
None
None
None

Format code

---

README.md
f1pystats/__init__.py
f1pystats/f1pystats.py
f1pystats/qualifying_results.py
f1pystats/sprint_results.py
tests/test_data/first_3_qualifying_results_2022.json
tests/test_qualifying_results.py

Add qualifying_results into pkg-tests branch.

Merge main

---

.github/workflows/pylint.yml
f1pystats/__init__.py
tests/package_tests/base_test_class.py
tests/package_tests/test_constructor_standings.py
tests/package_tests/test_driver_standings.py
tests/package_tests/test_finishing_status.py
tests/package_tests/test_get_circuits.py
tests/package_tests/test_get_constructors.py
tests/package_tests/test_get_drivers.py
tests/package_tests/test_lap_times.py
tests/package_tests/test_pit_stops.py
tests/package_tests/test_qualifying_results.py
tests/package_tests/test_race_table.py
tests/package_tests/test_race_winners.py
tests/package_tests/test_sprint_results.py

Flake8 is a tool for checking if the code formatted correctly. It is good to have a coding style convention for a project and using flake8 is easy and popular among python projects.
No issue for this

Introduce flake8 style guide checker

---

f1pystats/f1pystats.py

fixed a bug in pit_stops()
Fixes #74

Fixed typo in pit_stops

---

f1pystats/f1pystats.py

Using ergast season list api we can pick the last item from the list and use the 'season' field for year validity checks
Fixes #79

Extract last season constants from the code

---

README.md

Specify minimu poetry version
Fixes https://github.com/alec-kr/F1PyStats/issues/83

Specify poetry minimum version

---

README.md

Added Contributors section, showing all the contributors, who have contributed to the project
Fixes #81

Updated Readme.md to show valuable contributors

---

.flake8
.github/workflows/python-package.yml
poetry.lock
pyproject.toml

Installs Poetry and uses it for dependency setup and virtualenv execution in CI. If nothing has changed in the lockfile, use cached virtual environment.
See https://github.com/marketplace/actions/install-poetry-action#testing for an example workflow that I adapted for this project.
Fixes #85 
N/A
N/A

ci: Use Poetry for CI

---

.github/workflows/pylint.yml
.github/workflows/python-package.yml
README.md
poetry.lock
pyproject.toml

Update supported Python versions.
- discontinue 3.8
- initiate 3.11
#88 
update Python version if necessary
None.

Update supported versions

---

README.md
f1pystats/__init__.py
f1pystats/f1pystats.py
pyproject.toml
tests/test_data/api_data/all_circuits.json

Bump up some versions to 0.1.1.
None.
None.
None.

Bump up some version

---

f1pystats/f1pystats.py

Retry failed connection so that make the impact of timeout errors smaller.
None.
None.
None.

Retry failed connection

---

f1pystats/__init__.py
f1pystats/f1pystats.py
tests/module_tests/test_constructor_info.py
tests/module_tests/test_constructor_results.py
tests/module_tests/test_driver_info.py
tests/module_tests/test_driver_results.py
tests/module_tests/test_finishing_status.py
tests/module_tests/test_lap_times.py
tests/module_tests/test_pitstops.py
tests/module_tests/test_qualifying_results.py
tests/module_tests/test_race_circuits.py
tests/module_tests/test_race_schedule.py
tests/module_tests/test_race_winners.py
tests/module_tests/test_sprint_results.py

Fix linting warnigs below.
* I101 Imported names are in the wrong order.
* I201 Missing newline between import groups.
None.
None.
None.

Fix some linting warnings.

---

.github/workflows/pylint.yml

Fix [the error](https://github.com/alec-kr/F1PyStats/actions/runs/3864889916/jobs/6588021953) in the testing workflow.
#102 made ther error.
None.
None.

Add typing_extensions

---

pyproject.toml

Added @alec-kr to the authors entry in pyproject.toml
Fixes #111
None.
None.

Update the authors entry in pyproject.toml

---

f1pystats/f1pystats.py
poetry.lock
tests/package_tests/test_util.py

The following change were made to `f1pystats.get_sec()`.
* Enhance docstring
* Changed the function name and the argument name to better description
* Re-implement simply
* Add type hint
And Update my[py] 1.1.1.
None.
None.
None.

Refactoring a util function, get_sec()

---

docs/conf.py
poetry.lock
pyproject.toml

Workflows have been failed due to installation of `furo`.
This pull request uses `cloud-sptheme` instead of `furo`.
None.

Change theme to cloud-sptheme

---

.bumpversion.cfg
Release_inst.md
docs/conf.py
poetry.lock
pyproject.toml

Introduce `bump2version` to manage package version contained in the following files.
* `pyproject.toml`
* `docs/conf.py`
* `f1pystats/__init__.py`
I have also summarized the steps required for release in `Release_inst.md`.
None.

Introduce bump2version to manage package version

---

README.md
noxfile.py

Update `noxfile.py` to generate docs.
None.

Update noxfile.py to generate docs

---

CONTRIBUTING.md
README.md
docs/conf.py
noxfile.py
poetry.lock

Update noxfile.py to static check
* #128

Update noxfile.py to static check

---

CONTRIBUTING.md
noxfile.py

Update `tests` session on Nox.
* #128

Update tests session on Nox

---

.github/workflows/python-package.yml

Add macOS on the testing workflow.
* #129

Add macOS on the testing workflow.

---

.github/workflows/python-package.yml

Introduce testing on windows.
* #129

Add Windows on the testing workflow
